//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourisme.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcriviteAvi
    {
        public int Id { get; set; }
        public string AcriviteAvi_Titre { get; set; }
        public string AcriviteAvi_description { get; set; }
        public Nullable<double> AcriviteAvi_note { get; set; }
        public int AcriviteAvi_client_id { get; set; }
        public int AcriviteAvi_activite_id { get; set; }
        public Nullable<System.DateTime> AcriviteAvi_datecreation { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Activite Activite { get; set; }
    }
}
