//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourisme.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activite()
        {
            this.AcriviteAvis = new HashSet<AcriviteAvi>();
        }
    
        public int Id { get; set; }
        public string Activite_titre { get; set; }
        public string Activite_description { get; set; }
        public string Activite_image { get; set; }
        public int Activite_client_id { get; set; }
        public int Acrivite_poste_id { get; set; }
        public Nullable<System.DateTime> Acrivite_date_creation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcriviteAvi> AcriviteAvis { get; set; }
        public virtual Client Client { get; set; }
        public virtual Poste Poste { get; set; }
    }
}
