//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourisme.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int ID { get; set; }
        public int ClientID2 { get; set; }
        public int ClientID { get; set; }
        public string Demande_title { get; set; }
        public string Demande_description { get; set; }
        public Nullable<System.DateTime> Date_debut { get; set; }
        public Nullable<System.DateTime> Date_fin { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
