//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourisme.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poste()
        {
            this.Activites = new HashSet<Activite>();
            this.Avis = new HashSet<Avi>();
        }
    
        public int ID { get; set; }
        public int CategorieID { get; set; }
        public int ClientID2 { get; set; }
        public int ClientID { get; set; }
        public string Poste_title { get; set; }
        public string Poste_image { get; set; }
        public string Poste_description { get; set; }
        public Nullable<System.DateTime> Date_debut { get; set; }
        public Nullable<System.DateTime> Date_fin { get; set; }
        public Nullable<bool> Etat { get; set; }
        public Nullable<System.DateTime> Date_CreationPost { get; set; }
        public string Pay { get; set; }
        public string Ville { get; set; }
        public string Adress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activite> Activites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avi> Avis { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
